language: java
script:
- chmod 777 src/test/run_tests.sh
- src/test/run_tests.sh
- mvn test
env:
  global:
  - secure: HUfZqbNqVOU1tf1f7RUUWEp8upHRj6fq/ChpaoZ17yaa5qOWunjzhzxb4qEg+IKMfWFTWq590PiQYxz13BHmzLi9FKOQrbYiq3CNHolFU0y/hPNvX/JVZcovvNvrGfuyPrL0PG9fQ/CBDg6s0FZkXv0Oxf6NUuGHYWez57zOcOv0oE5DgPDq5/04g6JEUTsjqfQQzrgpBPjuwcU4IxDixaPSu4MQolFYW1p/QUHHSuNcouFwENMf+Nijbk9B3DhOb6aUA5q8odMd6idtXydjZONSFVgamef1pLwRReN9F2g6nWgsPFVZ/ejeIhAMTWVotYhet1MRLNVrkxGgY5yHqzBu6vi22nYLE5O+f45GbK+g8Cb7nkxUmFt4T4AkFZnz5j4Ys4YOjh/gBHz5JpVdFQVjhOy7KtqH5jfWWL+opgQU8fU870d0rB/1iHwUN5VP9QCQ1CeS92sY+2awJ8uiW8aLwTNWWN31t8GHFqS9o77SfoVDLoLN6mM/m9nOkATbAc08XuYN/OJ/MGsHUFsSt2PsK5XPQcc9+D7FR8nWtztZMSHgLJ5OnNIaxhRWqShBkrG99g6XZLxtr9FXWyFm0Tv+/Ajln35oLwgCL9FnU0BukIotF8o7Demu1JBzy4elpJ1Vy3WAn2T+EHnFphtcmeQxWFAi6hwe3Mlo1a5MPFQ=